// Legacy text constants — use useTranslation() from react-i18next in new components.
// This file is kept as fallback during migration.
export default {
  nav: {
    iniciarSesion: 'Iniciar sesión',
    rexistrarse: 'Rexistrarse',
    pecharSesion: 'Pechar sesión',
    pechando: 'Pechando sesión…',
    explorarMapas: 'Explorar mapas públicos',
    osMenusMapas: 'Os meus mapas',
    convites: 'Convites',
    visualizarMapas: 'Visualizar mapas',
    configuracion: 'Configuración',
    perfil: 'Perfil',
  },
  auth: {
    login: {
      benvida: 'Benvida de volta',
      subtitulo: 'Inicia sesión na túa conta.',
      titulo: 'Iniciar sesión',
      campoUsuaria: 'Nome de usuaria',
      campoClave: 'Contrasinal',
      botonEntrar: 'Entrar',
      cargando: 'Iniciando sesión…',
      textoFooter: '¿Non tes conta?',
      ligazonRexistro: '¿Non tes conta? Rexístrate',
      ligazonRexistroTexto: 'Rexístrate',
      errorCredenciais: 'Nome de usuaria ou contrasinal incorrectos.',
      errorXenerico: 'Produciuse un erro inesperado. Téntao de novo.',
      placeholderUsuaria: 'O teu nome de usuaria',
      placeholderClave: 'O teu contrasinal',
      validNomeObrigatorio: 'O nome de usuaria é obrigatorio.',
      validNomeCurto: 'O nome de usuaria debe ter polo menos 3 caracteres.',
      validNomeLongo: 'O nome de usuaria non pode superar 50 caracteres.',
      validClaveObrigatoria: 'O contrasinal é obrigatorio.',
      validClaveCurta: 'O contrasinal debe ter polo menos 8 caracteres.',
    },
    rexistro: {
      titulo: 'Crear conta',
      subtitulo: 'Comeza a crear e compartir os teus mapas personalizados.',
      campaNome: 'Nome',
      campoUsuaria: 'Nome de usuaria',
      campoCorreo: 'Correo electrónico',
      campoClave: 'Contrasinal',
      campoConfirmarClave: 'Confirmar contrasinal',
      botonRexistrar: 'Crear conta',
      cargando: 'Creando conta…',
      textoFooter: '¿Xa tes conta?',
      ligazonLogin: '¿Xa tes conta? Inicia sesión',
      ligazonLoginTexto: 'Inicia sesión',
      mensaxeExito: 'Conta creada. Xa podes iniciar sesión.',
      errorDuplicado: 'O rexistro fallou. O nome de usuaria ou o correo xa están en uso.',
      errorXenerico: 'Produciuse un erro inesperado. Téntao de novo.',
      placeholderNome: 'O teu nome',
      placeholderUsuaria: 'Escolle un nome de usuaria',
      placeholderCorreo: 'o.teu@correo.com',
      placeholderClave: 'Mínimo 8 caracteres',
      placeholderConfirmarClave: 'Repite o teu contrasinal',
      validNomeObrigatorio: 'O nome é obrigatorio.',
      validNomeCurto: 'O nome debe ter polo menos 3 caracteres.',
      validNomeLongo: 'O nome non pode superar 20 caracteres.',
      validUsernameObrigatorio: 'O nome de usuaria é obrigatorio.',
      validUsernameCurto: 'O nome de usuaria debe ter polo menos 4 caracteres.',
      validUsernameLongo: 'O nome de usuaria non pode superar 20 caracteres.',
      validCorreoObrigatorio: 'O correo electrónico é obrigatorio.',
      validCorreoCurto: 'O correo electrónico debe ter polo menos 8 caracteres.',
      validCorreoLongo: 'O correo electrónico non pode superar 50 caracteres.',
      validCorreoFormato: 'Introduce un enderezo de correo electrónico válido.',
      validClaveObrigatoria: 'O contrasinal é obrigatorio.',
      validClaveCurta: 'O contrasinal debe ter polo menos 8 caracteres.',
      validClaveLonga: 'O contrasinal non pode superar 40 caracteres.',
      validConfirmarClaveObrigatoria: 'Confirma o teu contrasinal.',
      validClavesNonCoiniciden: 'Os contrasinais non coinciden.',
    },
  },
  dashboard: {
    benvida: 'Benvida,',
    viaxeira: 'viaxeira',
    subtitulo: 'Estás autenticada. Os teus mapas están listos.',
    expiracioToken: 'Token expira:',
    navegacionRapida: 'Navegación rápida',
    descoñecido: 'Descoñecido',
  },
  mapas: {
    titulo: 'Os meus mapas',
    crearMapa: 'Novo mapa',
    botonNovo: '+ Novo mapa',
    crearPrimeiro: 'Crea o teu primeiro mapa',
    sinMapas: 'Aínda non tes ningún mapa. Crea o primeiro.',
    sinMapasSimple: 'Aínda non tes mapas.',
    campoNome: 'Nome do mapa',
    campoNomeLabel: 'Nome',
    campoDescripcion: 'Descrición',
    campoNomeLocalizacion: 'Nome da localización',
    campoVisibilidade: 'Visibilidade',
    opcionPublico: 'Público',
    opcionPrivado: 'Privado',
    etiquetaLocalizacion: 'Localización no mapa',
    axudaLocalizacionCrear: 'Fai clic no mapa para seleccionar a localización.',
    axudaLocalizacionEditar: 'Arrastra o marcador ou fai clic para cambiar a localización.',
    botonGardar: 'Gardar',
    botonCancelar: 'Cancelar',
    botonEditar: 'Editar',
    botonEliminar: 'Eliminar',
    botonCambiarVisibilidade: 'Cambiar visibilidade',
    botonDescargar: 'Descargar',
    botonCrear: 'Crear mapa',
    botonGardarCambios: 'Gardar cambios',
    tituloPaxinaCrear: 'Novo mapa',
    tituloPaxinaEditar: 'Editar mapa',
    voltarAosMapas: '← Volver aos mapas',
    voltarAoMapa: '← Volver ao mapa',
    confirmEliminarTitulo: 'Eliminar mapa',
    confirmEliminarMensaxe: 'Esta acción é irreversible. Eliminaranse tamén todos os marcadores e categorías asociados.',
    confirmEliminarBoton: 'Eliminar definitivamente',
    confirmEliminarCard: (nome) => `Eliminar o mapa "${nome}"? Esta acción non se pode desfacer.`,
    etiquetaPublico: 'Público',
    etiquetaPrivado: 'Privado',
    titleCambiarAPrivado: 'Cambiar a privado',
    titleCambiarAPublico: 'Cambiar a público',
    titleEliminar: 'Eliminar mapa',
    placeholderNome: 'Nome do mapa',
    placeholderDescripcion: 'Descrición opcional…',
    placeholderNomeLocalizacion: 'Ex: Santiago de Compostela',
    errorCargar: 'Non foi posible cargar os teus mapas. Inténtao de novo.',
    errorCargarMapa: 'Non foi posible cargar o mapa.',
    errorCrearMapa: 'Non foi posible crear o mapa. Inténtao de novo.',
    errorEditarMapa: 'Non foi posible gardar os cambios.',
    errorEliminarMapa: 'Non foi posible eliminar o mapa. Inténtao de novo.',
    validNomeObrigatorio: 'O nome é obrigatorio.',
    validNomeLongo: 'O nome non pode superar 100 caracteres.',
    validLocalizacionObrigatoria: 'A localización é obrigatoria.',
    validLocalizacionLonga: 'A localización non pode superar 200 caracteres.',
    validCoordsObrigatorias: 'Fai clic no mapa para seleccionar unha localización.',
  },
  marcadores: {
    titulo: 'Marcadores',
    engadirMarcador: 'Engadir marcador',
    campoNome: 'Nome do marcador',
    campoDescripcion: 'Descrición',
    campoCategoria: 'Categoría',
    sinCategoria: 'Sen categoría',
    botonGardar: 'Gardar',
    botonCancelar: 'Cancelar',
    botonEliminar: 'Eliminar',
    confirmEliminarTitulo: 'Eliminar marcador',
    confirmEliminarMensaxe: 'Vas eliminar este marcador. Esta acción non se pode desfacer.',
    confirmEliminarBoton: 'Eliminar',
  },
  categorias: {
    titulo: 'Categorías',
    engadirCategoria: 'Nova categoría',
    novaCategoria: 'Nova categoría',
    sinCategorias: 'Non hai categorías para este mapa.',
    campoNome: 'Nome',
    campoCor: 'Cor',
    campoIcona: 'Icona',
    placeholderNome: 'Nome',
    placeholderIcona: 'ex: star, home, flag',
    botonGardar: 'Gardar',
    botonCancelar: 'Cancelar',
    botonEditar: 'Editar',
    botonEliminar: 'Eliminar',
    confirmEliminarTitulo: 'Eliminar categoría',
    confirmEliminarMensaxe: 'Os marcadores asignados a esta categoría quedarán sen categoría.',
    confirmEliminarBoton: 'Eliminar',
    confirmEliminar: (nome) => `Eliminar a categoría "${nome}"?`,
    errorEliminar: 'Non foi posible eliminar a categoría.',
    errorGardar: 'Erro ao gardar',
    validNomeObrigatorio: 'O nome é obrigatorio.',
  },
  convites: {
    titulo: 'Convites',
    tituloPanel: 'Convidar usuaria',
    enviarConvite: 'Convidar usuaria',
    campoUsuaria: 'Nome de usuaria',
    placeholderUsuaria: 'Nome de usuaria',
    ariaConvidar: 'Nome de usuaria a convidar',
    botonConvidar: 'Convidar',
    botonEnviar: 'Enviar',
    enviando: 'Enviando…',
    botonAceptar: 'Aceptar',
    botonRexeitar: 'Rexeitar',
    botonCancelar: 'Cancelar',
    titleCancelar: 'Cancelar convite',
    recibidos: 'Convites recibidos',
    enviados: 'Convites enviados',
    tabEnviados: 'Enviados',
    tabRecibidos: 'Recibidos',
    subtituloEnviados: 'Convites enviados',
    sinConvites: 'Non hai convites pendentes.',
    sinConvitesEnviados: 'Non enviaches ningún convite.',
    sinConvitesRecibidos: 'Non recibiches ningún convite.',
    sinConvitesMapa: 'Non hai convites enviados para este mapa.',
    estadoPendente: 'Pendente',
    estadoAceptado: 'Aceptado',
    estadoRexeitado: 'Rexeitado',
    estadoCancelado: 'Cancelado',
    estadoExpirado: 'Expirado',
    cargandoPanel: 'Cargando…',
    conviteEnviado: (username) => `Convite enviado a ${username}.`,
    errorCargarPanel: 'Non foi posible cargar os convites.',
    errorCargarEnviados: 'Non foi posible cargar os convites enviados.',
    errorCargarRecibidos: 'Non foi posible cargar os convites recibidos.',
    errorEnviar: 'Non foi posible enviar o convite.',
    errorCancelar: 'Non foi posible cancelar o convite.',
    errorAceptar: 'Non foi posible aceptar o convite.',
    errorRexeitar: 'Non foi posible rexeitar o convite.',
  },
  erros: {
    xenerico: 'Produciuse un erro inesperado. Téntao de novo.',
    rede: 'Erro de conexión. Comproba a túa conexión a internet.',
    nonAutorizado: 'Non tes permiso para realizar esta acción.',
    nonAtopado: 'O recurso solicitado non existe.',
    sesionExpirada: 'A túa sesión expirou. Inicia sesión de novo.',
  },
  cargando: {
    xenerico: 'Cargando…',
    mapa: 'Cargando mapa…',
    mapas: 'Cargando mapas…',
    marcadores: 'Cargando marcadores…',
    gardando: 'Gardando…',
    eliminando: 'Eliminando…',
  },
  confirmar: {
    botonConfirmar: 'Confirmar',
    botonCancelar: 'Cancelar',
  },
  mapa: {
    buscadorPlaceholder: 'Buscar enderezo ou lugar…',
    localizacionActual: 'A miña localización',
    sinResultados: 'Non se atoparon resultados.',
    errorLocalizacion: 'Non foi posible obter a túa localización.',
  },
  contrasinal: {
    debil: 'Contrasinal débil',
    moderado: 'Contrasinal moderado',
    forte: 'Contrasinal forte',
  },
};
